name: Playwright Tests with Working Allure Reports

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
        
    - name: Install Playwright Browsers
      run: playwright install --with-deps
      
    - name: Create reports directories
      run: |
        mkdir -p reports
        mkdir -p allure-results
        
    - name: Run Playwright tests with Allure
      run: |
        pytest tests/ \
          --browser=${{ matrix.browser }} \
          --base-url="https://www.zanganehai.com" \
          --html=reports/report-${{ matrix.browser }}.html \
          --self-contained-html \
          --alluredir=allure-results \
          -v
          
    - name: Upload HTML test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: html-report-${{ matrix.browser }}
        path: reports/
        retention-days: 30
        
    - name: Upload Allure test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-results-${{ matrix.browser }}
        path: allure-results/
        retention-days: 30

  # Generate Allure report using different method
  allure-report:
    runs-on: ubuntu-latest
    needs: test
    if: always()
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Download all Allure results
      uses: actions/download-artifact@v4
      with:
        pattern: allure-results-*
        path: allure-results
        merge-multiple: true
        
    - name: Setup Java (required for Allure)
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: '17'
        
    - name: Install Allure CLI
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.tgz
        tar -zxf allure-2.24.0.tgz
        sudo mv allure-2.24.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure
        
    - name: Generate Allure Report
      run: |
        allure generate allure-results --clean -o allure-report
        
    - name: Add index.html for GitHub Pages
      run: |
        echo '<meta http-equiv="refresh" content="0; url=./allure-report/index.html" />' > index.html
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        keep_files: false